/** GENERATED — where Framer's runtime gets this site's text from now.
 *
 *  Framer's compiled chunks and CMS data carry their own copy of every string
 *  the runtime renders. Without this file, an edit to a copy.ts changes the
 *  HTML the server sends and nothing else: the runtime re-renders its own
 *  copy a moment later. src/render.ts reads this table on every render and
 *  regenerates those files from your source, so what the runtime renders is
 *  what you wrote. Regenerated by the converter; nothing to edit here. */
import { copy as copy0 } from "@/src/views/HomePage";
import { copy as copy1 } from "@/src/views/Section404Page";

export interface RuntimeText {
  /** Its key in public/assets/framer/fnj-content.mjs, when a chunk renders it. */
  key?: string;
  /** The CMS data files that carry it, when a collection page renders it. */
  cms?: string[];
  /** The text as converted — what the shipped files contain. */
  original: string;
  /** The text now, read from your source. */
  get: () => string | undefined;
}

/** 11 string(s) the runtime renders. */
export const runtimeText: RuntimeText[] = [
  { key: "theme", original: "THEME", get: () => copy0.theme },
  { key: "mi", original: "MI", get: () => copy0.mi },
  { key: "ds", original: "DS", get: () => copy0.ds },
  { key: "an", original: "AN", get: () => copy0.an },
  { key: "ti", original: "TI", get: () => copy0.ti },
  { key: "style", original: "STYLE", get: () => copy0.style },
  { key: "direction", original: "DIRECTION", get: () => copy0.direction },
  { key: "interval", original: "INTERVAL", get: () => copy0.interval },
  { key: "meteors", original: "METEORS", get: () => copy0.meteors },
  { key: "page_not_found", original: "Page Not Found", get: () => copy1.pageNotFound },
  { key: "back_to_home", original: "Back to Home", get: () => copy1.backToHome },
];

/** A collection record, as src/render.ts reads it: any field by name. */
export type CollectionRecord = { route: string } & Record<string, string | undefined>;

/** Every collection by name, for the member pages' hydration payloads. */
export const collections: Record<string, CollectionRecord[]> = {

};
