/** GENERATED — where Framer's runtime gets this site's text from now.
 *
 *  Framer's compiled chunks and CMS data carry their own copy of every string
 *  the runtime renders. Without this file, an edit to a copy.ts changes the
 *  HTML the server sends and nothing else: the runtime re-renders its own
 *  copy a moment later. src/render.ts reads this table on every render and
 *  regenerates those files from your source, so what the runtime renders is
 *  what you wrote. Regenerated by the converter; nothing to edit here. */
import { copy as copy0 } from "@/src/views/Section404Page";

export interface RuntimeText {
  /** Its key in public/assets/framer/fnj-content.mjs, when a chunk renders it. */
  key?: string;
  /** The CMS data files that carry it, when a collection page renders it. */
  cms?: string[];
  /** The text as converted — what the shipped files contain. */
  original: string;
  /** The text now, read from your source. */
  get: () => string | undefined;
}

/** 2 string(s) the runtime renders. */
export const runtimeText: RuntimeText[] = [
  { key: "page_not_found", original: "Page Not Found", get: () => copy0.pageNotFound },
  { key: "back_to_home", original: "Back to Home", get: () => copy0.backToHome },
];

/** A collection record, as src/render.ts reads it: any field by name. */
export type CollectionRecord = { route: string } & Record<string, string | undefined>;

/** Every collection by name, for the member pages' hydration payloads. */
export const collections: Record<string, CollectionRecord[]> = {

};
