"use client";
// Extracted solely from the supplied basketball-footer export. No Framer page runtime.
import { createElement as p, useEffect as o, useRef as i, useMemo as n, useCallback as h, useState as c } from "react";
import { getHoopLayout, drawHoop, drawHoopForeground, drawScoreDisplay } from "./courtGeometry";
import {unlockGameAudio,playGameSound} from "./gameAudio";
const l = typeof window !== "undefined" ? window : undefined;
const d = (callback) => callback();
const ie = () => false;
const Mo=.15, No=.16, Po=.16, Fo=0, Io=230;
const preventScroll = (event) => event.preventDefault();
const Lo={src:"/models/basketball.svg",alt:"Basketball"};
export default function BasketballGame(e){let{basketballs:t=[Lo],courtColor:r=`#b45309`,ballCount:a=8,ballSize:s=96,gravity:u=1.15,bounciness:f=.82,throwPower:m=1.25,hoop:g=!0,hoopX:_=84,hoopY:v=22,hoopScale:ee=100,rim:y=`#ea580c`,net:te=`rgba(255,255,255,0.92)`,showScore:b=!0,style:x}=e,ne=i(null),S=i(null),re=i(null),C=i(null),w=i(null),T=i(null),E=i(null),D=i(0),ae=i(-9999),oe=i([]),se=i([]),O=i([]),ce=i([]),k=i({body:null,points:[],anchor:null}),le=i({width:300,height:300,dpr:1}),A=i(300),ue=i(0),de=i(null),fe=ie(),[pe,me]=c(!0);
o(()=>{if(l===void 0)return;
let e=ne.current;
if(!e)return;
if(typeof IntersectionObserver>`u`){d(()=>{me(!0)});
return}let t=new IntersectionObserver(e=>{let t=e[0];
d(()=>{me(!!t?.isIntersecting)})},{threshold:.01});
return t.observe(e),()=>{t.disconnect()}},[]);
let he=n(()=>{let e=(t||[]).filter(e=>e?.src);
return e.length>0?e:[Lo]},[t]),j=h((e,t)=>e+Math.random()*(t-e),[]),M=h((e,t,n)=>Math.min(n,Math.max(t,e)),[]),ge=h((e,t,n,r,i,a,o,s,c)=>{e.save(),e.translate(n,r),e.rotate(o),e.scale(s,c),e.beginPath(),e.ellipse(0,0,i/2,a/2,0,0,Math.PI*2),e.clip(),e.drawImage(t,-i/2,-a/2,i,a),e.restore()},[]);
return o(()=>{if(l===void 0||!ne.current||!S.current)return;
let e=ne.current,t=S.current,n=t.getContext(`2d`);
if(!n)return;
const touchMove = event => { if(k.current.body) preventScroll(event); };
t.addEventListener("touchmove",touchMove,{passive:false});
let i=!1,o=!1,c=``,d=e=>{if(typeof document>`u`)return;
let t=document.body;
if(t){if(e){o||=(c=t.style.cursor,!0),t.style.cursor!==e&&(t.style.cursor=e);
return}o&&(t.style.cursor=c,o=!1,c=``)}},p=e=>{let t=Math.max(0,Fo),n=Math.max(0,e-80);
return e-Math.min(t,n)},h=()=>{let r=e.getBoundingClientRect(),i=Math.max(1,r.width),a=Math.max(1,r.height),o=Math.min(2.5,Math.max(1,l.devicePixelRatio||1));
t.width=Math.floor(i*o),t.height=Math.floor(a*o),t.style.width=`${i}px`,t.style.height=`${a}px`,le.current={width:i,height:a,dpr:o},A.current=p(a),n.setTransform(o,0,0,o,0,0)},x=()=>{A.current=p(le.current.height)},ie=(e,t)=>getHoopLayout(e,t),me=()=>{let{width:e,height:t}=le.current,n=ie(e,t);
E.current=n},N=()=>{let{width:e}=le.current,t=A.current;
O.current.forEach(n=>{let{body:r,width:i,height:a}=n,o=i/2,s=Math.max(o,e-i/2),c=a/2,l=Math.max(c,t-a/2),u=M(r.x,o,s),d=M(r.y,c,l);
(u!==r.x||d!==r.y)&&(r.x=u,r.y=d,r.vx=0,r.vy=0)})},_e=async()=>{let e=he.map(e=>new Promise(t=>{if(!e?.src){t(null);
return}let n=new Image;
n.crossOrigin=`anonymous`,n.decoding=`async`,n.onload=()=>t({img:n,aspect:n.naturalWidth&&n.naturalHeight?n.naturalWidth/n.naturalHeight:1}),n.onerror=()=>t(null),n.src=e.src})),t=await Promise.all(e);
ce.current=t.filter(e=>e!==null)},ve=()=>{let{width:e,height:t}=le.current,n=Math.max(1,Math.floor(a)),r=[],i=ce.current,o=Math.max(1,i.length),c=p(t),l=E.current,u=l?Math.max(40,l.boundsLeft-16):e;
for(let e=0;
e<n;
e++){let t=e%o,a=i[t]?.aspect||1,l=1+j(-.15,Mo),d=Math.max(20,s*l),f=d,p=d/Math.max(.6,Math.min(1.4,a)),m=(e+.5)/n*u,h=M(m+j(-u*.08,u*.08),f/2+4,Math.max(f/2+4,u)),g=p/2,_=g+8,v=Math.max(_,Math.min(c-g-8,c*.55)),ee=j(_,v),y=j(-Math.PI,Math.PI);
r.push({body:{x:h,y:ee,vx:j(-.5,.5),vy:j(-.25,.25),angle:y,angularVelocity:j(-.05,.05),radius:d/2},imageIndex:t,width:f,height:p,squash:0,prevY:ee})}O.current=r},ye=(t,n)=>{let r=e.getBoundingClientRect();
return t>=r.left&&t<=r.right&&n>=r.top&&n<=r.bottom?{x:t-r.left,y:n-r.top}:null},be=e=>{if(de.current!==null||k.current.body)return;
let t=ye(e.clientX,e.clientY);
if(!t)return;
let n=[...O.current].reverse().find(e=>{let n=t.x-e.body.x,r=t.y-e.body.y;
return n*n+r*r<=e.body.radius*e.body.radius});
n&&(unlockGameAudio(),e.preventDefault(),e.stopPropagation(),de.current=e.pointerId,S.current.setPointerCapture(e.pointerId),S.current.style.touchAction=`none`,k.current.body=n,k.current.points=[{...t,t:performance.now()}],k.current.anchor=t,d(`grabbing`))},xe=e=>{let t=ye(e.clientX,e.clientY);
if(k.current.body&&de.current===e.pointerId){if(!k.current.body||!t)return;
d(`grabbing`);
let e=performance.now();
k.current.points.push({...t,t:e}),k.current.points.length>12&&k.current.points.shift(),k.current.anchor=t;
return}if(!t){d(null);
return}let n=O.current.some(e=>{let n=t.x-e.body.x,r=t.y-e.body.y;
return n*n+r*r<=e.body.radius*e.body.radius});
if(d(n?`grab`:null),de.current!==e.pointerId||!k.current.body)return;
let r=performance.now();
k.current.points.push({...t,t:r}),k.current.points.length>12&&k.current.points.shift(),k.current.anchor=t},Se=e=>{if(de.current!==e.pointerId)return;
let t=k.current.body;
if(!t)return;
let n=k.current.points,r=n[n.length-1],i=n[0];
for(let e=n.length-1;
e>=0&&r&&r.t-n[e].t<=100;
e--)i=n[e];
if(i&&r&&r.t>i.t){let e=r.t-i.t,n=(r.x-i.x)/e*16.67*m,a=(r.y-i.y)/e*16.67*m,o=Math.hypot(n,a);
if(o>55){let e=55/o;
n*=e,a*=e}t.shot=true,t.body.vx=n,t.body.vy=a,t.body.angularVelocity=M(n/260*m,-1.5,1.5)}k.current.body=null,k.current.points=[],k.current.anchor=null,de.current=null,S.current.style.touchAction=`none`;
let a=ye(e.clientX,e.clientY);
if(!a){d(null);
return}let o=O.current.some(e=>{let t=a.x-e.body.x,n=a.y-e.body.y;
return t*t+n*n<=e.body.radius*e.body.radius});
d(o?`grab`:null)},Ce=(e,t,n)=>{let r=e.body.x,i=e.body.y,a=t.body.x,o=t.body.y,s=a-r,c=o-i,l=s*s+c*c;
if(l<=1e-4)return;
let u=Math.sqrt(l),d=e.body.radius+t.body.radius;
if(u>=d)return;
let f=s/u,p=c/u,m=d-u;
e.body.x-=f*m*.5,e.body.y-=p*m*.5,t.body.x+=f*m*.5,t.body.y+=p*m*.5;
let h=t.body.vx-e.body.vx,g=t.body.vy-e.body.vy,_=h*f+g*p;
if(_>0)return;
let v=-(1+n)*_/2,ee=v*f,y=v*p;
e.body.vx-=ee,e.body.vy-=y,t.body.vx+=ee,t.body.vy+=y;
let te=-p,b=f,x=(h*te+g*b)*.03;
e.body.vx+=te*x,e.body.vy+=b*x,t.body.vx-=te*x,t.body.vy-=b*x},P=(e,t,n,r,i,a)=>{let o=t+r,s=n+i,c=M(e.body.x,t,o),l=M(e.body.y,n,s),u=e.body.x-c,d=e.body.y-l,f=u*u+d*d,p=e.body.radius;
if(f>=p*p)return;
let m=Math.max(1e-4,Math.sqrt(f)),h=u/m,g=d/m,_=p-m;
e.body.x+=h*_,e.body.y+=g*_;
let v=e.body.vx*h+e.body.vy*g;
v<0&&(e.body.vx-=(1+a)*v*h,e.body.vy-=(1+a)*v*g)},we=(e,t,n,r,i)=>{let a=e.body.x-t,o=e.body.y-n,s=Math.sqrt(a*a+o*o)||1e-4,c=e.body.radius+r;
if(s>=c)return;
let l=a/s,u=o/s,d=c-s;
e.body.x+=l*d,e.body.y+=u*d;
let f=e.body.vx*l+e.body.vy*u;
f<0&&(Math.abs(f)>1.5&&playGameSound("rim",Math.max(.35,Math.abs(f)/12)),e.body.vx-=(1+i)*f*l,e.body.vy-=(1+i)*f*u)},F=e=>{let{width:t}=le.current,n=A.current,r=E.current,i=Math.min(.95,Math.max(0,f)),a=e*.06,o=u*.11;
for(let e=0;
e<O.current.length;
e++){let s=O.current[e];
if(k.current.body===s&&k.current.anchor){let e=k.current.anchor.x,t=k.current.anchor.y,n=e-s.body.x,r=t-s.body.y;
s.body.vx+=n*Po*a*.18,s.body.vy+=r*Po*a*.18,s.body.vx*=Math.pow(.86,a),s.body.vy*=Math.pow(.86,a)}else s.body.vy+=o*a;
let c=1-Math.min(.35,.0092*a);
s.body.vx*=c,s.body.vy*=c,s.body.angularVelocity*=Math.pow(.99,a),s.body.x+=s.body.vx*a,s.body.y+=s.body.vy*a,s.body.angle+=s.body.angularVelocity*a;
let l=s.width/2,u=Math.max(l,t-s.width/2),d=s.height/2,f=Math.max(d,n-s.height/2);
if(s.body.x<l?(s.body.x=l,s.body.vx=Math.abs(s.body.vx)*i):s.body.x>u&&(s.body.x=u,s.body.vx=-Math.abs(s.body.vx)*i),s.body.y<d?(s.body.y=d,s.body.vy=Math.abs(s.body.vy)*i):s.body.y>f&&(s.body.y=f,s.shot&&!k.current.body&&(s.shot=false,window.dispatchEvent(new CustomEvent("portfolio:raven-miss"))),Math.abs(s.body.vy)>2&&playGameSound("bounce",Math.max(.4,Math.abs(s.body.vy)/12)),s.body.vy=-Math.abs(s.body.vy)*i,s.body.vx*=.98-No*.2),r){let e=r.backboardX-r.backboardWidth/2;
we(s,r.rimFrontX,r.rimY,r.pegRadius,.78),we(s,r.rimBackX,r.rimY,r.pegRadius,.78)}}for(let e=0;
e<O.current.length;
e++)for(let t=e+1;
t<O.current.length;
t++)Ce(O.current[e],O.current[t],i)},Te=e=>{if(g&&E.current)drawHoop(n,E.current,y,te,e-ae.current)},I=[`#f97316`,`#fbbf24`,`#ef4444`,`#3b82f6`,`#22c55e`,`#ffffff`],Ee=(e,t)=>{for(let n=0;
n<16;
n++){let n=j(-Math.PI,0),r=j(1.5,4.5);
oe.current.push({x:e,y:t,vx:Math.cos(n)*r,vy:Math.sin(n)*r,life:j(500,900),maxLife:900,color:I[Math.floor(Math.random()*I.length)],size:j(3,6),spin:j(-.2,.2),angle:j(0,Math.PI*2)})}se.current.push({x:e,y:t-12,vy:-.045,life:850,maxLife:850})},De=e=>{let t=oe.current;
for(let r=t.length-1;
r>=0;
r--){let i=t[r];
if(i.vy+=.0022*e,i.x+=i.vx*e*.06,i.y+=i.vy*e*.06,i.angle+=i.spin,i.life-=e,i.life<=0){t.splice(r,1);
continue}n.save(),n.globalAlpha=M(i.life/i.maxLife,0,1),n.translate(i.x,i.y),n.rotate(i.angle),n.fillStyle=i.color,n.fillRect(-i.size/2,-i.size/2,i.size,i.size),n.restore()}let r=se.current;
for(let t=r.length-1;
t>=0;
t--){let i=r[t];
if(i.y+=i.vy*e,i.life-=e,i.life<=0){r.splice(t,1);
continue}let a=1-i.life/i.maxLife;
n.save(),n.globalAlpha=M(i.life/i.maxLife,0,1),n.fillStyle=`#ffffff`,n.strokeStyle=`rgba(0,0,0,0.5)`,n.lineWidth=3,n.font=`800 ${18+a*6}px sans-serif`,n.textAlign=`center`,n.strokeText(`+1`,i.x,i.y),n.fillText(`+1`,i.x,i.y),n.restore()}},Oe=()=>{let e=E.current;
if(!g||!e)return;
let t=Math.min(e.rimFrontX,e.rimBackX)+e.pegRadius*1.4,n=Math.max(e.rimFrontX,e.rimBackX)-e.pegRadius*1.4;
n<=t||O.current.forEach(r=>{let{body:i}=r,a=i.y,o=i.x;
r.prevY<e.rimY&&a>=e.rimY&&i.vy>.8&&o>t&&o<n&&(r.shot=false,playGameSound("basket"),D.current+=1,window.dispatchEvent(new CustomEvent("portfolio:raven-basket",{detail:{score:D.current}})),ae.current=performance.now(),Ee(o,e.rimY)),r.prevY=a})},L=e=>{if(i)return;
let{width:t,height:a}=le.current,o=ue.current?e-ue.current:16.67,s=Math.min(50,o);
ue.current=e;
// Small physics steps prevent fast shots skipping into rim collisions.
const steps=Math.max(1,Math.ceil(s/4));
for(let step=0;step<steps;step++){F(s/steps);Oe();}
n.clearRect(0,0,t,a),n.fillStyle=r,n.fillRect(0,0,t,a);
let c=ce.current,u=A.current;
if(Te(e),O.current.forEach(e=>{let{body:t,width:r,height:i}=e,a=Math.max(0,u-(t.y+i/2)),o=Math.max(r,i)*3.5,s=1-Math.min(1,a/o),c=.28*s;
if(c<=.01)return;
let l=r*(.75+.25*s),d=Math.max(4,i*.18*(.5+.5*s));
n.save(),n.globalAlpha=c,n.fillStyle=`#000000`,n.beginPath(),n.ellipse(t.x,u-d/2,l/2,d/2,0,0,Math.PI*2),n.fill(),n.restore()}),O.current.forEach((e,t)=>{let{body:r}=e,i=c[e.imageIndex%Math.max(1,c.length)],a=i?i.img:null,o=Math.hypot(r.vx,r.vy);
o>9&&e.squash<.16&&(e.squash=Math.min(.16,o*.01)),e.squash*=Math.max(0,1-s*.012);
let l=1-e.squash,u=1+e.squash*.6;
a?ge(n,a,r.x,r.y,e.width,e.height,r.angle,u,l):(n.save(),n.translate(r.x,r.y),n.rotate(r.angle),n.scale(u,l),n.fillStyle=t%2==0?`#ea580c`:`#f97316`,n.beginPath(),n.ellipse(0,0,e.width/2,e.height/2,0,0,Math.PI*2),n.fill(),n.restore())}),g&&E.current&&drawHoopForeground(n,E.current,y,te,e-ae.current),g&&b&&E.current){let e=E.current;
drawScoreDisplay(n,e,D.current)}De(s),re.current=l.requestAnimationFrame(L)},ke=()=>{let{width:e,height:t}=le.current;
n.clearRect(0,0,e,t),n.fillStyle=r,n.fillRect(0,0,e,t),Te(0);
let i=ce.current;
if(O.current.forEach((e,t)=>{let{body:r}=e,a=i[e.imageIndex%Math.max(1,i.length)],o=a?a.img:null;
o?ge(n,o,r.x,r.y,e.width,e.height,r.angle,1,1):(n.save(),n.translate(r.x,r.y),n.rotate(r.angle),n.fillStyle=t%2==0?`#ea580c`:`#f97316`,n.beginPath(),n.ellipse(0,0,e.width/2,e.height/2,0,0,Math.PI*2),n.fill(),n.restore())}),g&&b&&E.current){let e=E.current;
drawScoreDisplay(n,e,D.current)}};
if((async()=>{h(),x(),me(),await _e(),!i&&(ve(),ke(),!(fe||!pe)&&(re.current=l.requestAnimationFrame(L)))})(),!fe&&pe){let t=()=>{w.current!==null&&l.clearTimeout(w.current),w.current=l.setTimeout(()=>{h(),x(),me(),N(),ke()},80)};
typeof ResizeObserver<`u`?(C.current=new ResizeObserver(t),C.current.observe(e)):(T.current=t,l.addEventListener(`resize`,t)),S.current.addEventListener(`pointerdown`,be,!0),S.current.addEventListener(`pointermove`,xe),S.current.addEventListener(`pointerup`,Se),S.current.addEventListener(`pointercancel`,Se)}return()=>{t.removeEventListener("touchmove",touchMove),i=!0,d(null),fe||(t.removeEventListener(`pointerdown`,be,!0),t.removeEventListener(`pointermove`,xe),t.removeEventListener(`pointerup`,Se),t.removeEventListener(`pointercancel`,Se),T.current&&=(l.removeEventListener(`resize`,T.current),null),C.current&&=(C.current.disconnect(),null),w.current!==null&&(l.clearTimeout(w.current),w.current=null),re.current!==null&&(l.cancelAnimationFrame(re.current),re.current=null)),E.current=null,O.current=[],ce.current=[],oe.current=[],se.current=[],k.current={body:null,points:[],anchor:null},de.current=null,ue.current=0}},[he,r,u,fe,pe,j,M,f,a,s,m,ge,g,_,v,ee,y,te,b]),p(`div`,{ref:ne,style:{position:`relative`,width:`100%`,height:`100%`,overflow:`hidden`,background:r,...x},children:p(`canvas`,{ref:S,style:{position:`absolute`,inset:0,width:`100%`,height:`100%`,display:`block`,touchAction:`none`,pointerEvents:`auto`},tabIndex:0,role:`application`,"aria-label":`Basketball game. Drag a ball and release upwards toward the hoop to shoot.`})})}