export const businessCardDefaults = {
  lanyardText: "TARUN DIXIT",
  lanyardColor: "#1c1c1e",
  lanyardTextColor: "rgba(255, 255, 255, 0.16)",
  name: "Tarun Dixit",
  photoSrc: "/profile/tarun-dixit.jpg",
  photoAlt: "Tarun Dixit — professional headshot",
  role: "Product Designer",
  currentFocusLabel: "Current Focus",
  currentFocus: "AI Products • Design Systems • SaaS",
  buildingLabel: "Currently Building",
  building: "Kumba AI",
  locationLabel: "Location",
  location: "Chandigarh, India",
  status: "Design-Certified",
  email: "hello@tarundixit.com",
  bgGradientStart: "#1a0a0f",
  bgGradientMiddle: "#2a1218",
  bgGradientEnd: "#0a0608",
  accentColor1: "#5c2438",
  accentColor2: "#3d1828",
  accentColor3: "#7a3450",
};
